"""Single source of truth for every REJECT_* code (rulebook §B.11).

Centralizing these guarantees the Pine strategy, backend, logs and dashboard all
speak the same vocabulary and nothing is rejected with an ad-hoc string.
"""
from __future__ import annotations

# --- transport / webhook ---
REJECT_BAD_SIGNATURE = "REJECT_BAD_SIGNATURE"
REJECT_MALFORMED = "REJECT_MALFORMED"
REJECT_DUPLICATE_SIGNAL = "REJECT_DUPLICATE_SIGNAL"
REJECT_SIGNAL_EXPIRED = "REJECT_SIGNAL_EXPIRED"
REJECT_UNKNOWN_SYMBOL = "REJECT_UNKNOWN_SYMBOL"
REJECT_SIGNAL_DEVIATION = "REJECT_SIGNAL_DEVIATION"

# --- strategy context ---
REJECT_4H_NEUTRAL = "REJECT_4H_NEUTRAL"
REJECT_1H_TREND_MISMATCH = "REJECT_1H_TREND_MISMATCH"
REJECT_NO_PULLBACK = "REJECT_NO_PULLBACK"
REJECT_NO_5M_TRIGGER = "REJECT_NO_5M_TRIGGER"

# --- filters ---
REJECT_SESSION = "REJECT_SESSION"
REJECT_NEWS_WINDOW = "REJECT_NEWS_WINDOW"
REJECT_SPREAD_HIGH = "REJECT_SPREAD_HIGH"
REJECT_SLIPPAGE = "REJECT_SLIPPAGE"
REJECT_TRIGGER_CANDLE_LARGE = "REJECT_TRIGGER_CANDLE_LARGE"
REJECT_VOLATILITY_LOW = "REJECT_VOLATILITY_LOW"
REJECT_VOLATILITY_HIGH = "REJECT_VOLATILITY_HIGH"
REJECT_GAP = "REJECT_GAP"

# --- stops / sizing ---
REJECT_STOP_TOO_TIGHT = "REJECT_STOP_TOO_TIGHT"
REJECT_STOP_TOO_WIDE = "REJECT_STOP_TOO_WIDE"
REJECT_POSITION_TOO_SMALL = "REJECT_POSITION_TOO_SMALL"
REJECT_SIZING_UNRELIABLE = "REJECT_SIZING_UNRELIABLE"

# --- portfolio / risk ---
REJECT_MAX_TRADES = "REJECT_MAX_TRADES"
REJECT_MAX_DAILY_LOSSES = "REJECT_MAX_DAILY_LOSSES"
REJECT_MAX_CONSEC_LOSSES = "REJECT_MAX_CONSEC_LOSSES"
REJECT_DAILY_LOSS_LIMIT = "REJECT_DAILY_LOSS_LIMIT"
REJECT_WEEKLY_LOSS_LIMIT = "REJECT_WEEKLY_LOSS_LIMIT"
REJECT_MAX_OPEN_RISK = "REJECT_MAX_OPEN_RISK"
REJECT_SYMBOL_ALREADY_OPEN = "REJECT_SYMBOL_ALREADY_OPEN"
REJECT_DUPLICATE_CANDLE = "REJECT_DUPLICATE_CANDLE"
REJECT_CORRELATED_EXPOSURE = "REJECT_CORRELATED_EXPOSURE"

# --- environment ---
REJECT_LIVE_TRADING_DISABLED = "REJECT_LIVE_TRADING_DISABLED"

ALL = {name for name, val in globals().items() if name.startswith("REJECT_")}
